name: Pipeline CI/CD Completo

on:
  push:
    branches: [ "main", "master" ]

jobs:
  # TAREA 1: Ejecutar Tests Unitarios
  probar-codigo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Ejecutar Tests
      # Este comando busca automáticamente cualquier test en la solución
      run: dotnet test 

  # TAREA 2: Construir Docker y Subir a la Nube
  construir-y-subir:
    needs: probar-codigo # Solo corre si los tests pasaron
    runs-on: ubuntu-latest
    steps:
      - name: Bajar código
        uses: actions/checkout@v3
      
      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Construir y Subir Imagen
        uses: docker/build-push-action@v4
        with:
          # IMPORTANTE: Le decimos que entre a la carpeta PricingService
          context: ./PricingService
          file: ./PricingService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pricingservice:latest